# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('idcard', models.CharField(max_length=20)),
                ('is_vip', models.BooleanField(default=False)),
                ('car_type', models.CharField(max_length=200)),
            ],
        ),
    ]
