# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('School', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
            ],
        ),
    ]
