# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField(default=False)),
                ('language', models.CharField(default='Python', max_length=200)),
                ('style', models.CharField(default='friendly', max_length=200)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
